#!/bin/bash
# PreToolUse hook (matcher: Edit|Write): protect regenerated and immutable files.
#   - benchmark/baseline.json: regenerated only by ./benchmark/run.sh
#     --record-baseline; a baseline you can hand-edit is not a baseline.
#   - docs/adr/NNNN-*.md that already exist: ADRs are append-only (ADR 0001);
#     amendments get a NEW ADR. Creating the next-numbered file is allowed.
# Exit 2 blocks the tool call and shows the message to Claude.
# Fail-open (exit 0) on unexpected input so the hook never bricks the session.

input="$(cat)"
command -v jq >/dev/null 2>&1 || exit 0

file="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null)"
[ -n "$file" ] || exit 0

case "$file" in
  *benchmark/baseline.json)
    echo "BLOCKED: benchmark/baseline.json is regenerated by './benchmark/run.sh --record-baseline', never hand-edited. If the baseline is wrong or stale, re-record it and commit the result." >&2
    exit 2
    ;;
  *docs/adr/*)
    base="$(basename "$file")"
    case "$base" in
      [0-9][0-9][0-9][0-9]-*.md)
        if [ -e "$file" ]; then
          echo "BLOCKED: $base already exists and ADRs are immutable once written (ADR 0001). To amend or reverse it, create a NEW ADR with the next number that names and supersedes it (use /adr)." >&2
          exit 2
        fi
        ;;
    esac
    ;;
esac

exit 0
